### ISSUE TITLE
Ignition Dome crash when trying to run Ogre2 on Nvidia card running nouveau drivers

### ISSUE THREAD

**Issue by clalancette** [gazebosim/gz-rendering#128]
My computer has an Nvidia GeForce GTX 1070 (NV130) card in it.  I'm currently running the nouveau drivers on kernel 5.7.8.  The glxinfo from that card is here: https://gist.github.com/clalancette/03a21867327fdcd13dd32bd320e21a4e

I've built ignition-dome from sources.  Here are the versions I'm currently using:
```
repositories:
  ign-cmake:
    type: git
    url: https://github.com/ignitionrobotics/ign-cmake
    version: 220e990588895e1a1773f2bea68f21c4b288e8f4
  ign-common:
    type: git
    url: https://github.com/ignitionrobotics/ign-common
    version: 48a670fc949760de8416760ce5e03b0151edd332
  ign-fuel-tools:
    type: git
    url: https://github.com/ignitionrobotics/ign-fuel-tools
    version: 9e5bec0df2703626df6a77d33b40d42e65ed01cf
  ign-gazebo:
    type: git
    url: https://github.com/ignitionrobotics/ign-gazebo
    version: 8ec8d66cc8a6b661a2db6ccae153a785287fa315
  ign-gui:
    type: git
    url: https://github.com/ignitionrobotics/ign-gui
    version: 58cedf4c96b4baf46a0c5c79234faf9e3dc4e924
  ign-launch:
    type: git
    url: https://github.com/ignitionrobotics/ign-launch
    version: 10f21dfe0bf4ffa2c4f9f4b0548054d33487159a
  ign-math:
    type: git
    url: https://github.com/ignitionrobotics/ign-math
    version: 6e80a49a17172bd24a39bf7316166f86413374cc
  ign-msgs:
    type: git
    url: https://github.com/ignitionrobotics/ign-msgs
    version: 424db1eeabd2561682173100daaa98932e299b7c
  ign-physics:
    type: git
    url: https://github.com/ignitionrobotics/ign-physics
    version: 5f987c5df0eb71237e2329a7ef61f73983ec41cb
  ign-plugin:
    type: git
    url: https://github.com/ignitionrobotics/ign-plugin
    version: 0f75e41d9c59b0f37562a25e16eb124dff783d2e
  ign-rendering:
    type: git
    url: https://github.com/ignitionrobotics/ign-rendering
    version: 42e20eda915fb6fc30dcbb4faffc359dceab26ac
  ign-sensors:
    type: git
    url: https://github.com/ignitionrobotics/ign-sensors
    version: 03e7f51295624be5d043f82b817a375bc127eefc
  ign-tools:
    type: git
    url: https://github.com/ignitionrobotics/ign-tools
    version: 6c6ed6a1308503a5a4865c610f6d99d607153b3a
  ign-transport:
    type: git
    url: https://github.com/ignitionrobotics/ign-transport
    version: d72d63ecf9c782c80ba6813a499111e3b9b13dea
  sdformat:
    type: git
    url: https://github.com/osrf/sdformat
    version: 5b53e44c161bc3ce9d31c30793e2b89c52494311
```

I can successfully build the entire workspace.  If I try to run one of the demos: `ign gazebo shapes.sdf`, I get a crash with a backtrace: https://gist.github.com/clalancette/193fd47c04c9a0ee1df5d736f47ad1ae

After some debugging with @mjcarroll and @azeey , we determined that the problem was that this demo was trying to use Ogre2.  If I switch to using Ogre1, everything works fine.

There are 2 separate problems here:
* It would be nice if this driver/ignition combination could work with Ogre2.  I'm not sure what is involved with that.
* It would be very helpful for the user if the failure wasn't a crash, and instead said something like "it doesn't look like Ogre2 is supported, try Ogre1 instead".

I'm happy to try out any fixes or give more information here.
